### ISSUE TITLE
Possible wrong attack level

### ISSUE THREAD

**Issue by exxod** [angheloko/mhr-builder#1]
Hello, I noticed that the Rathalos Braces S show and use 1 level of attack while it should be of level 2.
Great job on this amazing application!

https://github.com/angheloko/mhr-builder/blob/fe61306ba46df538ce422b0f3e1547525fb06dc5/content/arms-armors.json#L1141

**Comment by angheloko** [comment]
Hey, thanks a lot for taking the time to report the issue and I'm glad you like it!

You are right, the data is wrong and [have been fixed](https://github.com/angheloko/mhr-builder/commit/731dd75f39e27625b55d8cece882b664b1bc8dbc).
