### ISSUE TITLE
Kushala Cocoon X 

### ISSUE THREAD

**Issue by Celeo** [angheloko/mhr-builder#14]
Blessing 1, agitator 3 in game.

![image](https://user-images.githubusercontent.com/772507/180339425-3f4f6712-3d26-4b72-8a71-76f7e8dca5b1.png)

![image](https://user-images.githubusercontent.com/772507/180339448-a2d46205-ed10-4a9c-86b4-453b9d54dac4.png)

Thanks for the tool!

**Comment by angheloko** [comment]
Thanks a lot for reporting this issue. It has been fixed!
