### ISSUE TITLE
Level 4 Decorations Give 1 Skill Point

### ISSUE THREAD

**Issue by arroncroft** [angheloko/mhr-builder#20]
Every level 4 decorations (at least as far as I've seen) gives 2 points in their chosen skill in-game. In the builder, they only provide 1 point for each decoration, which is usually the same as the level 3 version of the same decorations. Not a bug per se, but there's also no dropdown option for level 4 decorations when adding new ones.

For example, the Draw Jewel+ 4 should add 2 levels of Critical Draw.
![decoration_bug](https://user-images.githubusercontent.com/26657118/181872687-06975176-e379-4802-8482-0a56b1c621e5.PNG)
![decoration_select](https://user-images.githubusercontent.com/26657118/181872686-171821ff-d525-4109-a067-8a2f9ed9ade8.PNG)

**Comment by angheloko** [comment]
The issues has been fixed. You can now search level 4 decorations and adding them would increase the skill level correctly. There are some decorations that add more than 2 levels such as https://monsterhunterrise.wiki.fextralife.com/Hard+Defense+Jewel+++4 and those should work too.

Thanks a lot for reporting this issue!
