### ISSUE TITLE
Correction: Barioth Mail S & Rathalos Coil S

### ISSUE THREAD

**Issue by shugowah** [angheloko/mhr-builder#28]
(Sorry, one more. Thank you for such a helpful tool!)

Barioth Mail S has two lv2 decos and one lv1, shows as none in the sim

![image](https://user-images.githubusercontent.com/43919735/183987936-35204017-b4cb-4e27-a381-f8b94b917546.png)

**Comment by shugowah** [comment]
Another one, Rathalos Coil S has one lv2 deco slot

![image](https://user-images.githubusercontent.com/43919735/184010661-b0de9eef-52e0-4ff2-8326-d6fb6e8bf3ad.png)

**Comment by shugowah** [comment]
Another, Ingot Greaves S has a lv1 deco slot
![image](https://user-images.githubusercontent.com/43919735/184010983-8965ae6d-4b0d-444e-949d-2ea5218e394b.png)

**Comment by angheloko** [comment]
Hi @shugowah , thank you so much for reporting these issues! I've fixed them. I'm glad you were able to find the tool helpful despite the issues!
