### ISSUE TITLE
New Update?

### ISSUE THREAD

**Issue by KingQuigils** [angheloko/mhr-builder#29]
This isn't much of an issue but more of a request, when is the armour and skills from the new title update coming

**Comment by angheloko** [comment]
Hi @KingQuigils I'll be updating in the coming week or 2. I usually wait for other sites like https://monsterhunterrise.wiki.fextralife.com/ to have their info updated too. It seems from the patch notes though that there wasn't a huge update in terms or weapons and equipments: https://www.nintendolife.com/news/2022/08/monster-hunter-rise-sunbreaks-title-update-1-is-out-tomorrow-here-are-the-patch-notes

**Comment by KingQuigils** [comment]
Alright, Thank you, hope you're enjoying the title update

**Comment by angheloko** [comment]
Hi @KingQuigils I've added some missing skills and equiptments. I must've missed them! Thanks for bring this up.
