### ISSUE TITLE
Tigerclaw Glaive Deco Slot

### ISSUE THREAD

**Issue by exxod** [angheloko/mhr-builder#3]
hello! I noticed that the Tigerclaw Glaive is missing a 1 slot level 1 decoration.

https://monsterhunterrise.wiki.fextralife.com/Tigerclaw+Glaive

https://github.com/angheloko/mhr-builder/blob/fe61306ba46df538ce422b0f3e1547525fb06dc5/content/insect-glaive-weapons.json#L301

**Comment by angheloko** [comment]
Fixed! Thanks for the report! 🤝
