### ISSUE TITLE
Elemental Jewel 1 and 2

### ISSUE THREAD

**Issue by Jesskeez** [angheloko/mhr-builder#30]
I've noticed that Bolt Jewel 1 and Stream Jewel 1 add 2 element to the sets and Bolt and Stream Jewel 2 add 1 element to the sets. Not too hard to figure out and work around but it confuses my friend every time I show him sets

**Comment by don-ew** [comment]
@Jesskeez thank you for reporting this issue! I have deployed the fix.

**Comment by angheloko** [comment]
@Jesskeez thank you for reporting this issue! I have deployed the fix.
