### ISSUE TITLE
Switch Axe missing in Weapon Selection

### ISSUE THREAD

**Issue by Big0Toe** [angheloko/mhr-builder#31]
Hi,

first of all. Thanks a lot for this Builder. It works great and it's easy to manage builds and I love it!

Now the "issue":

- It seems that the Switch Axe "Vengeful Fellcleave" is missing in the weapon selection. I've looked through the other weapons, to see if it might have a wrong label, but it's not available. It's prior version "Tormented Shadowslice" can be found tho.
This is the Link to the weapon on fextralife: [Vengeful Fellcleave](https://monsterhunterrise.wiki.fextralife.com/Vengeful+Fellcleave)

Another minor thing: 

- it seems that the skill "Furious" shares it's description with "Maximum Might"; minor thing really since it's just sth you have to keep in mind but still wanted to at least mention it :)
Furious Skill Description: [Furious](https://monsterhunterrise.wiki.fextralife.com/Furious)
If you'd like the furious stuff as a separate issue I'll do that, just let me know.
![MHR builder_mm](https://user-images.githubusercontent.com/113671749/190598220-9e6bd260-50e3-4582-a466-01ae2b1192cc.PNG)
![MHR builder_fur](https://user-images.githubusercontent.com/113671749/190598222-2b74341d-5148-4e27-afe9-6980388bb40c.PNG)

Appreciate the work you're doing here! Helps a ton!

Greetings
BToe

**Comment by angheloko** [comment]
Hi @Big0Toe , thank you for taking the time and effort to report these issues! I have fixed them.

I'm glad you found it helpful in someway.

Happy hunting!
