### ISSUE TITLE
Demonlord Sledge

### ISSUE THREAD

**Issue by Romanmir** [angheloko/mhr-builder#32]
I'm pretty sure that the Demonlord Sledge doesn't have a 3210 ATK. Everywhere else I've looked seems to have this weapon at 320 ATK.

I found two sources that have the ATK as 320.
https://game8.co/games/Monster-Hunter-Rise/archives/383149
https://monsterhunterrise.wiki.fextralife.com/Demonlord+Sledge

**Comment by angheloko** [comment]
Thank you for reporting this issue! This has been fixed.
