### ISSUE TITLE
Nightstrix+ missing Decoration

### ISSUE THREAD

**Issue by juberberry** [angheloko/mhr-builder#33]
Hi there.

Loooove the MHR Armor tool. 

In the game, the Nightstrix+ has a Rampage Decoration 1, and a Decoration 2. 
The tool is missing the standard decoration slot.
![image](https://user-images.githubusercontent.com/120657196/207883529-7e00e6c6-bd71-4611-b52a-4ce676d4a990.png)

Thanks, J

**Comment by angheloko** [comment]
Thank you for reporting this issue! This has been fixed. Happy hunting!
