### ISSUE TITLE
Small errors in armor skills

### ISSUE THREAD

**Issue by mitharas** [angheloko/mhr-builder#36]
Hi, 
just noticed the following wrong skills on items:  
Orangaten Mail; Recovery Up should be Recovery Speed
Yukumo Sky Hakama: Recovery Up should be +2. Curiously fextralife got this wrong as well, so I attached a screenshot. ![yukumo sky](https://user-images.githubusercontent.com/8302737/215224041-2c2eebd8-bd5a-4041-921b-29171c323b5d.png)

**Comment by angheloko** [comment]
Thank you for reporting this issue! This has been fixed. Happy hunting!
