### ISSUE TITLE
Resetting sets

### ISSUE THREAD

**Issue by BigPotatoPete** [angheloko/mhr-builder#4]
Hi, I love this app a lot and really appreciate your work.
I've been having an issue where when I generate a set, my older sets are removed and I cannot get them back. Which isn't a serious issue but it's a pretty annoying thing to happen.
Hopefully you can do something about this in the near future.

**Comment by angheloko** [comment]
I'm glad you liked it!

I like your suggestion. It's especially useful when running different builds and weapons. I'll be adding this soon!

Thanks for taking the time to feedback!

**Comment by BigPotatoPete** [comment]
That’s great, thank you! From: DonSent: Tuesday, 15 June 2021 9:47 PMTo: angheloko/mhr-builderCc: BigPotatoPete; AuthorSubject: Re: [angheloko/mhr-builder] Resetting sets (#4) I'm glad you liked it!I like your suggestion. It's especially useful when running different builds and weapons. I'll be adding this soon!Thanks for taking the time to feedback!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by angheloko** [comment]
Added feature 99df33c4a29387139b7e36e8948d140ab7906f4c.

**Comment by angheloko** [comment]
Hi there, sets can now be pinned / unpinned. Pinned sets will not be removed when generating sets. Sets can be pinned by selecting the "Pin" option from the set's menu.

**Comment by BigPotatoPete** [comment]
That’s actually a great idea. Good job Sent from Mail for Windows 10 From: DonSent: Thursday, 17 June 2021 1:57 AMTo: angheloko/mhr-builderCc: BigPotatoPete; AuthorSubject: Re: [angheloko/mhr-builder] Resetting sets (#4) Hi there, sets can now be pinned / unpinned. Pinned sets will not be removed when generating sets. Sets can be pinned by selecting the "Pin" option from the set's menu.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
