### ISSUE TITLE
Import build

### ISSUE THREAD

**Issue by MatteoZanolla97** [angheloko/mhr-builder#44]
Hello, i exported the build and it copied a json string to my clipboard, and that works fine.
The thing I would like to know (or would like you to implement) is in the website where i can import it to re-generate the build I just did.
I'm italian and don't write in english often, i hope i was clear enough exposing my request.

P.S. I appreciated your work, this builder is very intuitive and easy to use, as well as useful to efficently build a set.

**Comment by angheloko** [comment]
Hi, I wasn't able to complete importing of JSON string. You could try and copy the link to your set instead. When you use that link, you'll see a preview of the set and from there you'll be able to copy it to your set list via the "Copy set" button.

<img width="661" alt="image" src="https://github.com/angheloko/mhr-builder/assets/3428999/d72b2802-72c2-4d62-bbb9-c748eb2951aa">

I really appreciate the feedback and I'm glad you find it helpful! Unfortunately, I'm no longer able to maintain the project. I hope you find continuous use for it, or even better, able to find a better alternative.

Happy hunting!
