### ISSUE TITLE
Nargacuga Helm S Slot

### ISSUE THREAD

**Issue by Lordreaper12** [angheloko/mhr-builder#6]
System: Nintendo Switch
Game: Monster Hunter Rise
Game Version.3.2.0

This information was visually checked

The Nargacuga Helm S slot is incorrect. It is currently set as a 2 slot on the builder. In game it shows as a 3 slot. 
![2021080218504995](https://user-images.githubusercontent.com/88357166/127945175-a5b26a10-4057-4141-8e1d-762ec3ba8587.png)

**Comment by angheloko** [comment]
Thanks a lot for reporting this issue! This has now been fixed.
