### ISSUE TITLE
Nargacuga Mail S Skills

### ISSUE THREAD

**Issue by Lordreaper12** [angheloko/mhr-builder#7]
System: Nintendo Switch
Game: Monster Hunter Rise
Game Version.3.2.0

This information was visually checked

The Nargacuga Mail S skill in the set builder is incorrect. "Critical Eye" is set to 1. In game it is actually 2
![Nargacuga Mail S](https://user-images.githubusercontent.com/88357166/127946423-34e80b7e-f732-43f1-9baa-5f62ffeb9a67.png)

**Comment by angheloko** [comment]
Thanks a lot for reporting this issue! This has now been fixed.
