### ISSUE TITLE
Nargacuga Coil S Skill

### ISSUE THREAD

**Issue by Lordreaper12** [angheloko/mhr-builder#8]
System: Nintendo Switch
Game: Monster Hunter Rise
Game Version.3.2.0

This information was visually checked

The Nargacuga Coil S skill in the set builder is incorrect. "Evade Extender" is set to 1. In game it is actually 2

![Nargacuga Coil S](https://user-images.githubusercontent.com/88357166/127946922-d3235392-c758-4260-8b4c-1552a0cdb26a.png)

**Comment by angheloko** [comment]
Thanks a lot for reporting this issue! This has now been fixed.
